# My Dataset Configuration v5 - just text / handwriting / backgrounds

v6.1:
  - more handwriting datasets
  - more colors

v6.0:
  - add typewriter class

workers: 4
final_size: 448
dataset_length: 20000
drive_mappings:
  "B:": "G:/s3/synthetic_data/resources/backgrounds/synthetic_backgrounds/dalle"
output_path: "C:/Users/tarchibald/github/document_embeddings/document_embeddings/segmentation/dataset/v6.0_20k"
overwrite: false
output_img_size: 448
composite_function: composite_the_images_torch
layout_sampler_kwargs:
  default_min_layers: 2
  default_max_layers: 5
  number_of_layer_weights:
    - .1
    - .3
    - .3
    - .2

datasets:
  - name: RenderedFonts
    type: PrintedTextGenerator
    layer_contents: "text"
    base_dataset_kwargs:
      saved_fonts_folder: "G:/s3/synthetic_data/resources/fonts"
      font_size_rng: [ 8, 50 ]
      word_count_rng: [ 10, 20 ]
      font_class_weights: [ 20, 40 ]
      font_class_files:
        - "G:/s3/synthetic_data/resources/fonts/FONT_SAMPLES/italic_fonts.pkl"
        - "G:/s3/synthetic_data/resources/fonts/FONT_SAMPLES/APPROVED_fonts.pkl"
    sample_weight: 5
    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        #- RandomDistortions
        #- RuledSurfaceDistortions
        - Blur
        #- BlurThreshold
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        #- Lighten
        #- ConditionalContrast
      - ToTensor
      - RandomResize:
          min_scale: .8
          max_scale: 1.5

  - name: RenderedFonts
    type: PrintedTextGenerator
    layer_contents: "typewriter"
    base_dataset_kwargs:
      saved_fonts_folder: "G:/s3/synthetic_data/resources/fonts"
      font_size_rng: [ 8, 30 ]
      word_count_rng: [ 10, 20 ]
      font_class_weights: [ 100 ]
      font_class_files:
        - "G:/s3/synthetic_data/resources/fonts/FONT_SAMPLES/typewriter_fonts.pkl"
    sample_weight: 5
    transforms:
      - ToNumpy
      - RandomChoice:
        - Blur
        - ColorJitter
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
      - ToTensor
      - RandomResize:
          min_scale: .8
          max_scale: 1.5

  - name: handwriting
    type: HWGenerator
    layer_contents: handwriting
    base_dataset_kwargs:
        img_dirs:
          - "C:/Users/tarchibald/Anaconda3/envs/docgen_windows/hwgen/resources/generated"
    sample_weight: 5
    transforms:
      - ToNumpy
      - RandomChoice:
        #- ColorJitter
        #- RandomDistortions
        #- RuledSurfaceDistortions
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - ColorJitter
        - Blur
        #- ConditionalContrast
      - MoreContrast
      - ToTensor
      - RandomResize:
          min_scale: 1
          max_scale: 1.5
    composite_function:
        type: CompositerTorch
        method: torchmul
    mask:
      type: SoftMask
      kwargs:
        threshold: .8

  - name: background
    type: NaiveImageFolder
    base_dataset_kwargs:
      # "B:/document_backgrounds/paper_only"
      img_dirs:
#        - "B:/document_backgrounds/paper_only/old paper with many ink marks, crinkles, wrinkles, and imperfections and variable lighting"
#        - "B:/document_backgrounds/paper_only/paper with many ink marks, crinkles, wrinkles, and imperfections and variable lighting"
#        - "B:/document_backgrounds/paper_only/white paper with many ink marks, crinkles, wrinkles, and imperfections and variable lighting"
#        - "B:/document_backgrounds/paper_only/aged blank letter with imprints of text from the reverse side, as if some vestiges of the ink permeated through the paper, but impossible to read; full frame"
#        - "B:/document_backgrounds/paper_only/aged blank letter with subtle imprints of text from its other side, as if the ink permeated through the paper; full frame"
#        - "B:/document_backgrounds/paper_only/blank paper with a some random highlighter and marker marks, full frame"
#        - "B:/document_backgrounds/paper_only/blank paper with mold damage, full frame"
#        - "B:/document_backgrounds/paper_only/old blank paper with a some random highlighter and marker marks, full frame"
#        - "B:/document_backgrounds/paper_only/old blank paper with water or coffee stains, full frame"
#        - "B:/document_backgrounds/paper_only/old blank paper, some wrinkles and imperfections, variable lighting"
#        - "B:/document_backgrounds/paper_only/old paper with ink marks, crinkles, wrinkles, and imperfections and variable lighting"
#        - "B:/document_backgrounds/with_backgrounds/"
        - "B:/document_backgrounds/with_backgrounds/full frame aerial view of 2 blank pages of old open book with wrinkles; book is on top of a noisey background"
        - "B:/document_backgrounds/with_backgrounds/microfilm blank old page with ink marks"
        - "B:/document_backgrounds/with_backgrounds/old blank weathered document"
        - "B:/document_backgrounds/with_backgrounds/old microfilm blank document"
        - "B:/document_backgrounds/with_backgrounds/2 blank pages of old book, full frame"
        - "B:/document_backgrounds/with_backgrounds/aerial view of 2 blank pages of old open book with ink marks and wrinkles, full frame"
        - "B:/document_backgrounds/with_backgrounds/aerial view of 2 blank pages of old open book, full frame"
        #- "B:/document_backgrounds/with_backgrounds/blank discolored paper with creases; it is stapled along the top, bottom, and sides, also has paperclips"
        - "B:/document_backgrounds/with_backgrounds/blank old document"
        - "B:/document_backgrounds/paper_only/aged blank letter with subtle imprints of text from its other side, as if the ink permeated through the paper; full frameG:/s3/synthetic_data/resources/backgrounds/synthetic_backgrounds/dalle/document_backgrounds/paper_only/aged blank letter with subtle imprints of text from its other side, as if the ink permeated through the paper; full frameG:/s3/synthetic_data/resources/backgrounds/synthetic_backgrounds/dalle/document_backgrounds/paper_only/aged blank letter with subtle imprints of text from its other side, as if the ink permeated through the paper; full frame/light"
    layer_contents: noise
    layer_position: 0 # background layer
    sample_weight: 8
    percent_overlap: 1
    mask:
      type: GrayscaleMask
    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        - RandomDistortions
        - RuledSurfaceDistortions
        - Blobs
        - Blobs
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform

      - ToTensor
# This will mess up the bounding boxes
#      - RandomBottomLeftEdgeCrop
#      - RandomFlipOrMirror
#      - RandomResize:
#          min_scale: .5
#          max_scale: 2

  - name: pdf_text
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        - "G:/s3/forms/PDF/OPM/text/images"
        - "G:/s3/forms/PDF/SSA/text/images"
    layer_contents: text
    sample_weight: 1
    transforms:
      - ToNumpy
      - RandomChoice:
        #- RandomDistortions
        #- RuledSurfaceDistortions
        - ConditionalContrast
        #- Blur
        - BlurThreshold
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - ColorJitter
      - ToTensor
      - RandomResize:
          min_scale: .5
          max_scale: 2
          max_upscale: 3

  - name: pdf_form_elements
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        - "G:/s3/forms/PDF/IRS/other_elements/images"
        - "G:/s3/forms/PDF/GDC/other_elements/images/good"
        - "G:/s3/forms/PDF/OPM/other_elements/images"
        - "G:/s3/forms/PDF/SSA/other_elements/images"
      recursive: false
    layer_contents: form_elements
    sample_weight: 2
    transforms:
      - ToNumpy
      - RandomChoice:
        - RandomDistortions
        - RuledSurfaceDistortions
        - ConditionalContrast
        #- Lighten
        - Blur
        #- ColorJitter
        - RandomRotate
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - ColorJitter

      - ToTensor
      - RandomResize:
          min_scale: .5
          max_scale: 1.8
          max_upscale: 3
    mask:
      type: SoftMask
      kwargs:
        threshold: .8

    filters:
      - RejectIfTooManyPixelsAreBelowThreshold:
          threshold: 0.9
          max_percent_of_pixels_allowed_below_threshold: 0.15

  - name: handwriting_images_dalle
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        #- "G:/s3/synthetic_data/FRENCH_BMD/v2.4.3_10k_french_with_fonts"
        #- "G:/s3/synthetic_data/FRENCH_BMD/FRENCH_BMD_LAYOUTv2.1.0/1000"
        #- "B:/document_backgrounds/handwriting"
        - B:/document_backgrounds/handwriting/enhanced/0
        - B:/document_backgrounds/handwriting/enhanced/4
        - B:/document_backgrounds/handwriting/enhanced/5
      recursive: true
      #file_name_filter: "[2-9][0-9]_"

    layer_contents: handwriting
    sample_weight: 2
    filters:
      - RejectIfTooManyPixelsAreBelowThreshold:
          threshold: 0.8
          max_percent_of_pixels_allowed_below_threshold: 0.4
    mask:
      type: SoftMask
      kwargs:
        threshold: .6

    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        - RandomRotate
        #- RandomDistortions
        #- RuledSurfaceDistortions
        - Blur
        #- ConditionalContrast
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform

      - ToTensor
      - RandomResize:
          min_scale: .8
          max_scale: 1.3
#      - CropBorder:
#            border_size_rng: 200
    composite_function:
        type: CompositerTorch
        method: torchmul

  - name: handwriting_images_iam
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        - "G:/data/standard_hwr/IAM_OFFLINE/lines"
        - "G:/data/standard_hwr/AllHandwritingImages/"
      recursive: true
    layer_contents: handwriting
    sample_weight: 10
    filters:
      - RejectIfTooManyPixelsAreBelowThreshold:
          threshold: 0.8
          max_percent_of_pixels_allowed_below_threshold: 0.4
    mask:
      type: SoftMask
      kwargs:
        threshold: .6

    transforms:
      - ToNumpy
      - CropToDarkness

      - RandomChoice:
        - ColorJitter
        #- RandomDistortions
        #- RuledSurfaceDistortions
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - Blur
        #- ConditionalContrast
      - MoreContrast
      - ToTensor
      - RandomResize:
          min_scale: .9
          max_scale: 1.1
    composite_function:
        type: CompositerTorch
        method: torchmul

  - name: generated_form_elements
    type: PreprintedFormElementGenerator
    layer_contents:
      - form_elements
    sample_weight: 1
    transforms:
      - ToNumpy
      - RandomChoice:
#          - ColorJitter
#          - RandomDistortions
#          - RuledSurfaceDistortions
#          - ConditionalContrast
          - Lighten
          - RandomRotate
          - IdentityTransform
          - IdentityTransform
          - IdentityTransform
#          - Blur
      - ToTensor
      - RandomResize:
          min_scale: .8
          max_scale: 4
    mask:
      type: Mask # anything dark at all should be considered a line
      kwargs:
        threshold: .99


  - name: images
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs: "G:/s3/synthetic_data/resources/images"
    layer_contents: seals_and_images
    sample_weight: 0
    mask:
      type: mask
      kwargs:
        threshold: .99
    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        - RandomDistortions
        - RuledSurfaceDistortions
        - Blur
        - Lighten
        - Contrast
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform

      - ToTensor
      - ResizeLongestSide:
          longest_side: [ 24, 128 ]

  - name: seals
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs: "G:/s3/synthetic_data/resources/seals"
    layer_contents: seals_and_images # seals, text
    sample_weight: 0
    transforms:
      - ToNumpy
      - RandomChoice:
        - RandomDistortions
        - RuledSurfaceDistortions
        - ColorJitter
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
        - IdentityTransform
      - ToTensor
      - ResizeLongestSide:
          longest_side: [ 24, 128 ]


transforms_after_compositing:

background_bounding_boxes_pkl_path: "G:/s3/synthetic_data/resources/backgrounds/synthetic_backgrounds/dalle/document_backgrounds/with_backgrounds/bounding_boxes_FILESTEM_BOUNDINGBOX.pkl"
