workers: 5
final_size: 448
dataset_length: 100000
drive_mappings:
  "B:": "G:/s3/synthetic_data/resources/backgrounds/synthetic_backgrounds/dalle"
output_path: "C:/Users/tarchibald/github/document_embeddings/document_embeddings/segmentation/dataset/v9_100k"
overwrite: false
output_img_size: 448
composite_function: composite_the_images_torch
layout_sampler_kwargs:
  default_min_layers: 1
  default_max_layers: 5
  number_of_layer_weights:
    - .01 # 1 layer
    - .3
    - .3
    - .3
    - .2

datasets:
  - name: RenderedFonts
    type: PrintedTextGenerator
    layer_contents: "text"
    base_dataset_kwargs:
      saved_fonts_folder: "G:/s3/synthetic_data/resources/fonts"
      font_size_rng: [ 8, 40 ]
      word_count_rng: [ 10, 20 ]
    sample_weight: 2
    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        - RandomDistortions
        - RuledSurfaceDistortions
        - Blur
        - Lighten
        - ConditionalContrast
      - ToTensor
      - RandomResize:
          min_scale: .25
          max_scale: 2

  - name: handwriting
    type: HWGenerator
    layer_contents: handwriting
    base_dataset_kwargs:
        img_dirs:
          - "C:/Users/tarchibald/Anaconda3/envs/docgen_windows/hwgen/resources/generated"
    sample_weight: 1
    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        - RandomDistortions
        - RuledSurfaceDistortions
        #- Blur
        - ConditionalContrast
      - ToTensor
      - RandomResize:
          min_scale: .5
          max_scale: 1.5
    composite_function:
        type: CompositerTorch
        method: torchmul
    mask:
      type: SoftMask
      kwargs:
        threshold: .8

  - name: background
    type: NaiveImageFolder
    base_dataset_kwargs:
      # "B:/document_backgrounds/paper_only"
      img_dirs:
        - "B:/document_backgrounds/paper_only/old paper with many ink marks, crinkles, wrinkles, and imperfections and variable lighting"
        - "B:/document_backgrounds/paper_only/paper with many ink marks, crinkles, wrinkles, and imperfections and variable lighting"
        - "B:/document_backgrounds/paper_only/white paper with many ink marks, crinkles, wrinkles, and imperfections and variable lighting"
        - "B:/document_backgrounds/paper_only/aged blank letter with imprints of text from the reverse side, as if some vestiges of the ink permeated through the paper, but impossible to read; full frame"
        - "B:/document_backgrounds/paper_only/aged blank letter with subtle imprints of text from its other side, as if the ink permeated through the paper; full frame"
        - "B:/document_backgrounds/paper_only/blank paper with a some random highlighter and marker marks, full frame"
        - "B:/document_backgrounds/paper_only/blank paper with mold damage, full frame"
        - "B:/document_backgrounds/paper_only/old blank paper with a some random highlighter and marker marks, full frame"
        - "B:/document_backgrounds/paper_only/old blank paper with water or coffee stains, full frame"
        - "B:/document_backgrounds/paper_only/old blank paper, some wrinkles and imperfections, variable lighting"
        - "B:/document_backgrounds/paper_only/old paper with ink marks, crinkles, wrinkles, and imperfections and variable lighting"
    layer_contents: noise
    layer_position: 0 # background layer
    sample_weight: 4
    percent_overlap: 1
    mask:
      type: GrayscaleMask
    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        - RandomDistortions
        - RuledSurfaceDistortions
      - ToTensor
      - RandomBottomLeftEdgeCrop
      - RandomResize:
          min_scale: .5
          max_scale: 2

  - name: pdf_text
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        - "G:/s3/forms/PDF/OPM/text/images"
        - "G:/s3/forms/PDF/SSA/text/images"
    layer_contents: text
    sample_weight: 1
    transforms:
      - ToNumpy
      - RandomChoice:
        - RandomDistortions
        - RuledSurfaceDistortions
        - ConditionalContrast
        - Lighten
        - Blur

      - ToTensor
      - RandomResize:
          min_scale: .1
          max_scale: 2
          max_upscale: 3

  - name: pdf_form_elements
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        - "G:/s3/forms/PDF/IRS/other_elements/images"
        - "G:/s3/forms/PDF/GDC/other_elements/images"
        - "G:/s3/forms/PDF/OPM/other_elements/images"
        - "G:/s3/forms/PDF/SSA/other_elements/images"
    layer_contents: form_elements
    sample_weight: 2
    transforms:
      - ToNumpy
      - RandomChoice:
        - RandomDistortions
        - RuledSurfaceDistortions
        - ConditionalContrast
        - Lighten
        - Blur
        - ColorJitter
      - ToTensor
      - RandomResize:
          min_scale: .1
          max_scale: 1.8
          max_upscale: 3
    mask:
      type: SoftMask
      kwargs:
        threshold: .6

    filters:
      - RejectIfTooManyPixelsAreBelowThreshold:
          threshold: 0.9
          max_percent_of_pixels_allowed_below_threshold: 0.1

  - name: handwriting_images_dalle
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        #- "G:/s3/synthetic_data/FRENCH_BMD/v2.4.3_10k_french_with_fonts"
        #- "G:/s3/synthetic_data/FRENCH_BMD/FRENCH_BMD_LAYOUTv2.1.0/1000"
        - "B:/document_backgrounds/handwriting"
      recursive: true
      file_name_filter: "[2-9][0-9]_"

    layer_contents: handwriting
    sample_weight: 1
    filters:
      - RejectIfTooManyPixelsAreBelowThreshold:
          threshold: 0.8
          max_percent_of_pixels_allowed_below_threshold: 0.4
    mask:
      type: SoftMask
      kwargs:
        threshold: .6

    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        #- RandomDistortions
        - RuledSurfaceDistortions
        #- Blur
        #- ConditionalContrast
      - ToTensor
      - RandomResize:
          min_scale: .3
          max_scale: 1.5
      - CropBorder:
            border_size_rng: 200
    composite_function:
        type: CompositerTorch
        method: torchmul

  - name: handwriting_images_iam
    type: NaiveImageFolder
    base_dataset_kwargs:
      img_dirs:
        - "G:/data/standard_hwr/IAM_OFFLINE/lines"
      recursive: true
    layer_contents: handwriting
    sample_weight: 2
    filters:
      - RejectIfTooManyPixelsAreBelowThreshold:
          threshold: 0.8
          max_percent_of_pixels_allowed_below_threshold: 0.4
    mask:
      type: SoftMask
      kwargs:
        threshold: .6

    transforms:
      - ToNumpy
      - RandomChoice:
        - ColorJitter
        #- RandomDistortions
        - RuledSurfaceDistortions
        #- Blur
        #- ConditionalContrast
      - ToTensor
      - RandomResize:
          min_scale: .1
          max_scale: 1.1
    composite_function:
        type: CompositerTorch
        method: torchmul


  - name: generated_form_elements
    type: PreprintedFormElementGenerator
    layer_contents:
      - form_elements
    sample_weight: 1
    transforms:
      - ToNumpy
      - RandomChoice:
#          - ColorJitter
#          - RandomDistortions
#          - RuledSurfaceDistortions
#          - ConditionalContrast
          - Lighten
          - Blur
      - ToTensor
      - RandomResize:
          min_scale: .8
          max_scale: 4
    mask:
      type: SoftMask
      kwargs:
        threshold: .85


transforms_after_compositing:

